"""
Minimal worked example for the VPIN implementation.

    python example.py

Generates a SYNTHETIC trade tape (see the warning below), computes VPIN with
both classification methods, prints a summary and writes
outputs/example_output.csv.

=============================================================================
THE SAMPLE DATA IS SYNTHETIC. It is generated by the function below from a
fixed random seed. It is NOT real market data, it is not a recording of any
actual instrument, and no conclusion about any real security can be drawn
from it. It exists only so the implementation can be run and verified
end-to-end without a paid tick-data subscription.
=============================================================================
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

from vpin import vpin_from_trades

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = 20260808


def make_synthetic_trades(n_trades: int = 20_000, seed: int = SEED) -> pd.DataFrame:
    """Synthetic tape with a deliberately planted one-sided episode.

    Three regimes, so the measure has something to detect:
      * trades      0 - 7,999  balanced two-sided flow
      * trades  8,000 -11,999  informed buying: persistent upward drift
      * trades 12,000 -19,999  balanced again

    VPIN should rise through the middle regime and decay afterwards. That is
    the behaviour being demonstrated - not a claim about real markets.
    """
    rng = np.random.default_rng(seed)

    drift = np.zeros(n_trades)
    drift[8_000:12_000] = 0.0040            # the informed episode

    steps = rng.normal(0.0, 0.01, n_trades) + drift
    price = 100.0 + np.cumsum(steps)

    # Lognormal trade sizes: a few large prints, many small ones.
    volume = np.round(rng.lognormal(mean=5.2, sigma=0.9, size=n_trades))
    volume = np.clip(volume, 1, None)

    return pd.DataFrame({
        'timestamp': pd.date_range('2026-01-05 14:30:00', periods=n_trades,
                                   freq='100ms', tz='UTC'),
        'price': np.round(price, 4),
        'volume': volume.astype(int),
    })


def main() -> int:
    trades = make_synthetic_trades()
    total_volume = trades['volume'].sum()

    # 50 buckets per "day" of this synthetic tape is a reasonable granularity.
    bucket_size = int(total_volume / 250)
    window = 50

    print('=' * 68)
    print('VPIN example  --  SYNTHETIC DATA, NOT REAL MARKET DATA')
    print('=' * 68)
    print(f'trades          : {len(trades):,}')
    print(f'total volume    : {total_volume:,}')
    print(f'bucket size     : {bucket_size:,}')
    print(f'rolling window  : {window} buckets')
    print(f'price range     : {trades.price.min():.2f} - {trades.price.max():.2f}')
    print()

    results = {}
    for method in ('bvc', 'tick'):
        out = vpin_from_trades(trades, bucket_size=bucket_size,
                               window=window, method=method)
        results[method] = out
        valid = out['vpin'].dropna()
        print(f'[{method.upper():4}] buckets={len(out):3d}  '
              f'VPIN mean={valid.mean():.4f}  '
              f'min={valid.min():.4f}  max={valid.max():.4f}')

    bvc = results['bvc']

    # Volume conservation: buckets must account for all consumed volume.
    consumed = bvc['volume'].sum()
    print(f'\nvolume in buckets : {consumed:,.0f} '
          f'({consumed / total_volume:.1%} of tape; remainder is the '
          f'incomplete final bucket, discarded by design)')

    # Did VPIN respond to the planted episode?
    n = len(bvc)
    quiet = bvc['vpin'].iloc[int(n * 0.15):int(n * 0.35)].mean()
    active = bvc['vpin'].iloc[int(n * 0.42):int(n * 0.62)].mean()
    print(f'\nmean VPIN, balanced regime : {quiet:.4f}')
    print(f'mean VPIN, informed regime : {active:.4f}')
    print(f'ratio                      : {active / quiet:.2f}x')

    os.makedirs(os.path.join(HERE, 'outputs'), exist_ok=True)
    cols = ['bucket_id', 'close_price', 'volume', 'n_trades',
            'buy_volume', 'sell_volume', 'order_imbalance', 'vpin']
    out_path = os.path.join(HERE, 'outputs', 'example_output.csv')
    bvc[cols].round(4).to_csv(out_path, index=False)
    print(f'\nwrote {out_path}')

    sample_path = os.path.join(HERE, 'sample_data', 'sample_trades.csv')
    os.makedirs(os.path.dirname(sample_path), exist_ok=True)
    trades.head(2_000).to_csv(sample_path, index=False)
    print(f'wrote {sample_path}  (first 2,000 rows of the synthetic tape)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
