"""Copy shown ONLY on a session with zero BUY signals.

Kept out of quantum-signals.html so it is not served to crawlers on the
95% of days when it is false. The page said "No BUY signals today" in its
markup while 67 BUY signals existed; hiding it with display:none was no
defence, because crawlers and language models read hidden text. The
pipeline now writes this in only when buy_count is genuinely zero.
"""

NO_BUY_MSG = 'No BUY signals today. All stocks are on WATCH — below the signal confluence threshold.'

NO_BUY_CTX = '\n      <h3 style="font-family:\'Barlow Condensed\',sans-serif;font-size:16px;font-weight:700;color:var(--text);margin:0 0 10px;letter-spacing:.2px">How to Interpret a Watch-Only Day</h3>\n      <p style="font-size:13px;color:var(--dim);line-height:1.75;margin:0 0 12px">A day with no BUY signals is not a malfunction — it is the system working as intended. The confluence threshold exists precisely to avoid publishing low-conviction setups. When fewer than 22 bullish signals align on any stock, the engine returns no output rather than forcing a signal where none exists.</p>\n      <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px 32px;margin-top:4px">\n        <div>\n          <div style="font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;letter-spacing:.6px;text-transform:uppercase;color:var(--accent);margin-bottom:6px">What it means</div>\n          <p style="font-size:12px;color:var(--dim);line-height:1.7;margin:0">The current market environment does not meet the multi-factor conditions the engine requires. This can occur during high-volatility regimes, after sharp corrective moves, or during consolidation phases where trend, momentum, and volume signals are not simultaneously bullish.</p>\n        </div>\n        <div>\n          <div style="font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;letter-spacing:.6px;text-transform:uppercase;color:var(--accent);margin-bottom:6px">What to do</div>\n          <p style="font-size:12px;color:var(--dim);line-height:1.7;margin:0">Review the <a href="markets.html" style="color:var(--accent)">live market dashboard</a> for macro context — elevated VIX, yield curve stress, or broad index weakness often explains why stocks are failing the confluence test. Use the time to review methodology and prepare watchlists for when conditions improve.</p>\n        </div>\n        <div>\n          <div style="font-family:\'Barlow Condensed\',sans-serif;font-size:11px;font-weight:700;letter-spacing:.6px;text-transform:uppercase;color:var(--accent);margin-bottom:6px">Historical frequency</div>\n          <p style="font-size:12px;color:var(--dim);line-height:1.7;margin:0">Watch-only days are a normal and recurring output. In high-volatility periods, they can cluster across consecutive sessions. A return to active BUY signals typically follows regime stabilization — when trend, momentum, and volume indicators re-align across the scan universe.</p>\n        </div>\n      </div>\n    '
